// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	FeedID        uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          sql.NullString
	Url           sql.NullString
	UserID        uuid.UUID
	LastFetchedAt sql.NullTime
}

type FeedFollow struct {
	FeedFollowID uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       uuid.UUID
	FeedID       uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      sql.NullString
	ApiKey    string
}
